name: Convert Dictionaries

on:
  push:
    paths:
      - 'abbrev2full/abbrev2full_ms_ime.txt'
      - 'abbrev2full/abbrev2full_google_ime.txt'
      - 'abbrev_conv/abbrev_conv_ms_ime.txt'
      - 'abbrev_conv/abbrev_conv_google_ime.txt'

jobs:
  convert_to_google_ime:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'abbrev2full/abbrev2full_ms_ime.txt') ||
      contains(github.event.head_commit.modified, 'abbrev_conv/abbrev_conv_ms_ime.txt')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Convert MS-IME to Google IME (abbrev2full)
        if: contains(github.event.head_commit.modified, 'abbrev2full/abbrev2full_ms_ime.txt')
        run: |
          python scripts/convert.py abbrev2full/abbrev2full_ms_ime.txt abbrev2full/abbrev2full_google_ime.txt shift_jis utf-8
          git add abbrev2full/abbrev2full_google_ime.txt

      - name: Convert MS-IME to Google IME (abbrev_conv)
        if: contains(github.event.head_commit.modified, 'abbrev_conv/abbrev_conv_ms_ime.txt')
        run: |
          python scripts/convert.py abbrev_conv/abbrev_conv_ms_ime.txt abbrev_conv/abbrev_conv_google_ime.txt shift_jis utf-8
          git add abbrev_conv/abbrev_conv_google_ime.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Auto-converted to Google IME from MS-IME'
          branch: 'auto-convert-to-google-ime'
          title: 'Auto-convert to Google IME from MS-IME'
          body: |
            This pull request was automatically generated by GitHub Actions.
            It converts the updated MS-IME files to Google IME files with UTF-8 encoding.
          labels: |
            auto-generated
            conversion

  convert_to_ms_ime:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'abbrev2full/abbrev2full_google_ime.txt') ||
      contains(github.event.head_commit.modified, 'abbrev_conv/abbrev_conv_google_ime.txt')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Convert Google IME to MS-IME (abbrev2full)
        if: contains(github.event.head_commit.modified, 'abbrev2full/abbrev2full_google_ime.txt')
        run: |
          python scripts/convert.py abbrev2full/abbrev2full_google_ime.txt abbrev2full/abbrev2full_ms_ime.txt utf-8 shift_jis
          git add abbrev2full/abbrev2full_ms_ime.txt
      
      - name: Convert Google IME to MS-IME (abbrev_conv)
        if: contains(github.event.head_commit.modified, 'abbrev_conv/abbrev_conv_google_ime.txt')
        run: |
          python scripts/convert.py abbrev_conv/abbrev_conv_google_ime.txt abbrev_conv/abbrev_conv_ms_ime.txt utf-8 shift_jis
          git add abbrev_conv/abbrev_conv_ms_ime.txt
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: Auto-converted to MS-IME from Google IME'
          branch: 'auto-convert-to-ms-ime'
          title: 'Auto-convert to MS-IME from Google IME'
          body: |
            This pull request was automatically generated by GitHub Actions.
            It converts the updated Google IME files to MS-IME files with Shift-JIS encoding.
          labels: |
            auto-generated
            conversion